version: "3"
services:
  server:
    container_name: hike-tracker-server
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: r3rumcc/hike-tracker22-13:server_v1.1
    command: npm start
    ports:
      - 3001:3001
  
  client:
    container_name: hike-tracker-client
    build: 
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    image: r3rumcc/hike-tracker22-13:client_v1.1
    ports:
      - 3000:3000
    depends_on: 
      - server